exports build script: clearer argument/environment handling

diff --git a/exports b/exports
--- a/exports
+++ b/exports
@@ -1,46 +1,47 @@
 # this is not a script, it is intended to be sourced,
 # so defined variables will be available at the current shell
 
-if test $# = 0; then
-	if test -f .config; then
-		. .config 2> /dev/null
-		board=$BR2_PROJECT
-		if test -n "$BLDDIR"; then
-			bdir=$BLDDIR
-		else
-			bdir=$PWD/build
-		fi
-	else
-		echo "No board defined nor .config found."
-		echo "Usage: . exports.sh [board ($(ls local | tr '\n' ' '))] [build dir]"
-	fi
-
-elif test $# = 1; then
-	board=$1
-	bdir=$PWD/build
-
-elif test $# = 2; then
-	board=$1
+if test $# = 2; then
 	bdir=$2
-fi
-
-if test -f ./local/$board/$board.config; then
-	if test -f .config; then
-		eval $(grep BR2_PROJECT .config)
-
-		if ! cmp -si $(head -n 4 local/$BR2_PROJECT/$BR2_PROJECT.config | wc -c):$(head -n 4 .config | wc -c) \
-			local/$BR2_PROJECT/$BR2_PROJECT.config .config; then
-			echo "Current .config for \"$BR2_PROJECT\" has changed," \
-				 "consider making \"make saveconfig\". Exiting."
-			board=$BR2_PROJECT
-			return
-		fi
-	fi
-	make BOARD=$board getconfig
+elif test -n "$BLDDIR"; then
+	bdir=$BLDDIR
 else
-	echo "No configuration ./local/$board/$board.config found for board $board"
-	return
+	bdir=$PWD/build
 fi
+
+if test -z "$bdir"; then
+	bdir=$PWD/build
+fi
+
+if test $# -ge 1; then
+	board=$1
+elif test -f .config; then
+	. .config 2> /dev/null
+	board=$BR2_PROJECT
+else
+	echo "No board defined nor .config found."
+	echo "Usage: . exports.sh [board ($(ls local | tr '\n' ' '))] [build dir]"
+	return 1
+fi
+
+if ! test -f ./local/$board/$board.config; then
+	echo "No configuration file ./local/$board/$board.config found"
+	return 1
+fi
+
+if test -f .config; then
+	eval $(grep BR2_PROJECT .config)
+
+	if ! cmp -si $(head -n 4 local/$BR2_PROJECT/$BR2_PROJECT.config | wc -c):$(head -n 4 .config | wc -c) \
+		local/$BR2_PROJECT/$BR2_PROJECT.config .config; then
+		echo "Current .config for \"$BR2_PROJECT\" has changed," \
+				"consider making \"make saveconfig\". Exiting."
+		board=$BR2_PROJECT
+		return 1
+	fi
+fi
+
+make BOARD=$board getconfig
 
 if false; then
 	if ! test -d $bdir; then
@@ -57,8 +58,8 @@ fi
 . .config 2> /dev/null
 
 if test "$board" != "$BR2_PROJECT"; then
-	echo "The board defined in ./local/$board/$board.config, \"$BR2_PROJECT\", does not match this script argument, \"$board\""
-	return
+	echo "The board defined in ./local/$board/$board.config is \"$BR2_PROJECT\", and it does not match the required \"$board\"."
+	return 1
 fi
 
 linux_version=$BR2_CUSTOM_LINUX26_VERSION
@@ -79,4 +80,4 @@ export EDITOR=uemacs
 
 make oldconfig
 
-echo Build ready for \"$board\"
+echo Build ready for \"$board\" at \"$BLDDIR\"
