-adapt the distributed rcscript to Alt-F "standards"

diff --git a/customroot/etc/init.d/S80mediatomb b/customroot/etc/init.d/S80mediatomb
--- a/customroot/etc/init.d/S80mediatomb
+++ b/customroot/etc/init.d/S80mediatomb
@@ -1,91 +1,90 @@
 #!/bin/sh
-#
-# mediatomb This script starts and stops the mediatomb daemon
-#
-# chkconfig: 2345 95 30
-# processname: mediatomb
-# description: mediatomb is a daemon process which provides a UPnP service
-# config: /etc/mediatomb
-# config: /etc/mediatomb/config.xml
-# pidfile: /var/run/mediatomb.pid
 
+NAME=mediatomb
+DESC="MediaTomb provides an A/V UPnP service"
+TYPE=user
 
-# Source function library.
-. /etc/rc.d/init.d/functions
+MT_USER="mediatomb"
+MT_GROUP="multimedia"
 
-# Source networking configuration.
-. /etc/sysconfig/network
+MT_PIDFILE="/var/run/mediatomb.pid"
+MT_LOGFILE="/var/log/mediatomb"
 
-# Check that networking is up.
-[ ${NETWORKING} = "no" ] && exit 0
+MT_HOME="/var/lib"
+MT_CFGDIR="mediatomb"
 
-# Set default mediatomb configuration.
+MT_PORT=50500
 
-# either make an installation in /etc/mediatomb and leave this blank,
-# or specify an alternative config file location using the -c option
-# Note: be aware, that -i parameter is used to set the ip of the 
-# interface specified above
+MT_ARGS="-d -u $MT_USER -g $MT_GROUP -P $MT_PIDFILE -l $MT_LOGFILE \
+-m $MT_HOME -f $MT_CFGDIR -p $MT_PORT -e eth0"
 
-. /etc/mediatomb.conf
+status() {
+	if start-stop-daemon -K -t -q -n $NAME; then
+		echo "$NAME running"
+		return 0
+	else
+		echo "$NAME stopped"
+		return 1
+	fi
+}
 
-###############################
-# make sure to run it as nobody
-MEDIATOMB="-d -u $MT_USER -g $MT_GROUP -P $MT_PIDFILE -l $MT_LOGFILE -m $MT_HOME -f $MT_CFGDIR -p $MT_PORT"
-
-[ -f /usr/bin/mediatomb ] || exit 0
-[ ${MT_INTERFACE} = "NOT_SET" ] && echo "Please edit /etc/mediatomb.conf and change \
-the MT_INTERFACE variable to your network device (eth0, eth1, etc.)" && exit 0
-
-PATH=$PATH:/usr/bin:/usr/local/bin
-
-# By default it's all good
-RETVAL=0
-
-# See how we were called.
 case "$1" in
   start)
-    # Start daemon.
-    echo -n "Applying multicast settings to $MT_INTERFACE... "
-    # those settings are necessary for us to react to M-SEARCH requests
-    route add -net 239.0.0.0 netmask 255.0.0.0 $MT_INTERFACE >/dev/null 2>&1
-    ifconfig $MT_INTERFACE allmulti
-    touch $MT_PIDFILE
-    chown mediatomb $MT_PIDFILE
+	echo -n "Starting $NAME: "
+	# Applying multicast settings to eth0
+	route add -net 239.0.0.0 netmask 255.0.0.0 eth0 >& /dev/null
+	ifconfig eth0 allmulti
+	touch $MT_PIDFILE
+	chown mediatomb $MT_PIDFILE
 
-    mkdir -p "/$MT_HOME/$MT_CFGDIR"
-    chown mediatomb "/$MT_HOME/$MT_CFGDIR"
-    
-    echo -n "Starting mediatomb: "
-    
-    daemon $NICELEVEL mediatomb $MEDIATOMB -e $MT_INTERFACE $MT_OPTIONS
-    
-    RETVAL=$?
-        echo
-        [ $RETVAL = 0 ] && touch /var/lock/subsys/mediatomb
-        ;;
+	start-stop-daemon --start --quiet --background --oknodo \
+		--exec $NAME -- $MT_ARGS
+	if test $? = 1; then
+		echo "Fail."
+		exit 1
+	fi
+	echo "OK."
+	exit 0
+	;;
+
   stop)
         # Stop daemons.
         echo -n "Shutting down mediatomb: "
-        killproc mediatomb
-        RETVAL=$?
-        echo
-        [ $RETVAL = 0 ] && rm -f /var/lock/subsys/mediatomb
+	start-stop-daemon -K -q -n $NAME
+	if test $? = 1; then
+		echo "Fail."
+		exit 1
+	fi
+	echo "OK."
+	exit 0	
         ;;
-  restart)
-        $0 stop
-        $0 start
-        ;;
-  condrestart)
-       [ -e /var/lock/subsys/mediatomb ] && $0 restart
-       ;;
-  status)
-    status mediatomb
-    RETVAL=$?
-    ;;
-  *)
-    echo "Usage: $0 {start|stop|restart|status|condrestart}"
-    RETVAL=1
-    ;;
-esac
 
-exit $RETVAL
+  reload)
+        echo -n "Reloading mediatomb: "
+	start-stop-daemon -K -q -s 1 -n $NAME
+	if test $? = 1; then
+		echo "Fail."
+		exit 1
+	fi
+	echo "OK."
+	exit 0	
+        ;;
+
+  restart|force-reload)
+	echo "Restarting $NAME: "
+	sh $0 stop
+	while start-stop-daemon -K -t -q -n $NAME; do usleep 200000; done
+	sh $0 start
+	echo ""
+        ;;
+
+  status)
+	status
+	;;
+
+  *)
+	echo "Usage: $0 {start|stop|restart|reload|force-reload|status}"
+	exit 1
+	;;
+
+esac
