couchpotato: verify download dir existence and ownership

diff --git a/customroot/etc/init.d/S81couchpotato b/customroot/etc/init.d/S81couchpotato
--- a/customroot/etc/init.d/S81couchpotato
+++ b/customroot/etc/init.d/S81couchpotato
@@ -15,6 +15,8 @@ CONFF=/etc/couchpotato.conf
 PID_PATH=/var/run/couchpotato
 PID_FILE=$PID_PATH/couchpotato.pid
 
+DL_DIR=$(sed -n 's/^destination[[:space:]]*=[[:space:]]*\(.*\)/\1/p' $CONFF)
+
 OPTS="--quiet -d --nolaunch --config=$CONFF --datadir=$DATA_DIR --pidfile=$PID_FILE"
 
 . $(dirname $0)/common
@@ -35,6 +37,17 @@ if ! test -h /var/log/couchpotato.log; then
     ln -sf $DATA_DIR/logs/CouchPotato.log /var/log/couchpotato.log
 fi
 
+if test "$(basename $DL_DIR)" = "Public"; then
+	echo "Fail: you have to configure CouchPotato first."
+	exit 1
+fi
+
+if ! test -d "$DL_DIR"; then
+	mkdir -p "$DL_DIR"
+	chown $USER:$GROUP "$DL_DIR"
+	chmod g+rwxs "$DL_DIR"
+fi
+
 case "$1" in
 	start)
 		echo -n "Starting $NAME: "
@@ -49,10 +62,10 @@ case "$1" in
 	status)
 		if start-stop-daemon -K -t -q --pidfile $PID_FILE; then
 			echo "$NAME running"
-			return 0
+			exit 0
 		else
 			echo "$NAME stopped"
-			return 1
+			exit 1
 		fi
 		;;
 	restart)
@@ -64,5 +77,3 @@ case "$1" in
         ;;
 	*) usage $0 "start|stop|status|restart" ;;
 esac
-
-exit 0
