sickbeard: verify download dir existence and ownership, small fixes

diff --git a/customroot/etc/init.d/S81sickbeard b/customroot/etc/init.d/S81sickbeard
--- a/customroot/etc/init.d/S81sickbeard
+++ b/customroot/etc/init.d/S81sickbeard
@@ -8,11 +8,12 @@ USER=sickbeard
 GROUP=TV
 
 DATA_DIR=/var/lib/sickbeard
-PROG_DIR=/opt/Sick-Beard
+PROG_DIR=/opt/SickBeard
 PROG=${PROG_DIR}/SickBeard.py
 CONFF=/etc/sickbeard.conf
+DL_DIR=$(sed -n 's/^root_dirs.*=.*|\(.*\)/\1/p' $CONFF)
 
-PID_PATH=/var/run/sickbeard/
+PID_PATH=/var/run/sickbeard
 PID_FILE=$PID_PATH/sickbeard.pid
 
 OPTS="--quiet --daemon --pidfile=$PID_FILE --config $CONFF --datadir=$DATA_DIR"
@@ -35,6 +36,17 @@ if ! test -h /var/log/sickbeard.log; then
     ln -sf $DATA_DIR/Logs/sickbeard.log /var/log/sickbeard.log
 fi
 
+if test "$(basename $DL_DIR)" = "Public"; then
+	echo "Fail: you have to configure SickBeard first."
+	exit 1
+fi
+
+if ! test -d "$DL_DIR"; then
+	mkdir -p "$DL_DIR"
+	chown $USER:$GROUP "$DL_DIR"
+	chmod g+rwxs "$DL_DIR"
+fi
+
 case "$1" in
 	start)
 		echo -n "Starting $NAME: "
@@ -49,10 +61,10 @@ case "$1" in
 	status)
 		if start-stop-daemon -K -t -q --pidfile $PID_FILE; then
 			echo "$NAME running"
-			return 0
+			exit 0
 		else
 			echo "$NAME stopped"
-			return 1
+			exit 1
 		fi
 		;;
 	restart)
@@ -64,5 +76,3 @@ case "$1" in
         ;;
 	*) usage $0 "start|stop|status|restart" ;;
 esac
-
-exit 0
