-detect missing start script (stale rc* links)

diff --git a/customroot/usr/sbin/rcscript b/customroot/usr/sbin/rcscript
--- a/customroot/usr/sbin/rcscript
+++ b/customroot/usr/sbin/rcscript
@@ -7,4 +7,7 @@ srp="/etc/init.d/S??${nm1}"
 
 if test -f $srp; then
 	sh $srp $1
+else
+	echo "$srp not found."
+	exit 1
 fi
