libdlna: fix ffmpeg includes patches; bump devel version

diff --git a/package/multimedia/libdlna/libdlna-0.2.3.patch b/package/multimedia/libdlna/libdlna-0.2.3.patch
--- a/package/multimedia/libdlna/libdlna-0.2.3.patch
+++ b/package/multimedia/libdlna/libdlna-0.2.3.patch
@@ -9,6 +9,18 @@
    ;;
    esac
  done
+@@ -610,9 +610,9 @@
+ fi
+ 
+ echolog "Checking for libavformat ..."
+-check_lib ffmpeg/avformat.h av_register_all -lavformat || die "Error, can't find libavformat !"
++check_lib libavformat/avformat.h av_register_all -lavformat || die "Error, can't find libavformat !"
+ echolog "Checking for libavcodec ..."
+-check_lib ffmpeg/avcodec.h avcodec_register_all -lavcodec || die "Error, can't find libavcodec !"
++check_lib libavcodec/avcodec.h avcodec_register_all -lavcodec || die "Error, can't find libavcodec !"
+ 
+ #################################################
+ #   version
 @@ -627,7 +627,8 @@
    return 0;
  }
