python: install pip (and setuptools) on the host and at install time on the target; bump devel version

diff --git a/ipkgfiles/python.postinst b/ipkgfiles/python.postinst
--- a/ipkgfiles/python.postinst
+++ b/ipkgfiles/python.postinst
@@ -1,5 +1,8 @@
 #!/bin/sh
 
+# because the ipkg order of dependent package postinstall scripts execution is reversed,
+# the duplicity package also execute those
+
 # python needs pyconfig.h and Makefile at runtime!
 
 PVER=2.7
@@ -7,7 +10,25 @@ PVER=2.7
 INCDIR=/usr/include/python$PVER
 CONFDIR=/usr/lib/python$PVER/config
 
-mkdir -p $INCDIR $CONFDIR
-mv /usr/lib/python$PVER/pyconfig.h $INCDIR
-mv /usr/lib/python$PVER/Makefile $CONFDIR
+PIP_SITE=https://bootstrap.pypa.io
+PIP_SOURCE=get-pip.py
 
+if ! test -f $INCDIR/pyconfig.h -o -f $CONFDIR/Makefile; then
+	mkdir -p $INCDIR $CONFDIR
+	mv /usr/lib/python$PVER/pyconfig.h $INCDIR
+	mv /usr/lib/python$PVER/Makefile $CONFDIR
+fi
+
+if ! test -f /usr/bin/pip -a -d /usr/lib/python$PVER/site-packages/pip; then
+	echo "Downloading pip... "
+	if ! wget -P /tmp --progress=dot:mega $PIP_SITE/$PIP_SOURCE -P /tmp/; then
+		echo "failed"
+		exit 1
+	fi
+	echo -n "Installing pip, please wait... "
+	if ! python /tmp/$PIP_SOURCE; then
+		echo "failed"
+		exit 1
+	fi
+	rm -f /tmp/$PIP_SOURCE
+fi
